apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: tbml-api
      app.kubernetes.io/component: tbml-api
      app.kubernetes.io/instance: tbml-api
      app.kubernetes.io/name: tbml-api
    name: tbml-api
    namespace: tbml
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: tbml-api
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: tbml-api
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/tbml/tbml-api:latest
          imagePullPolicy: IfNotPresent
          name: tbml-api
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
      type: Progressing
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
