apiVersion: v1
kind: Service
metadata:
  labels:
    app: tbml-api
    app.kubernetes.io/component: tbml-api
    app.kubernetes.io/instance: tbml-api
    app.kubernetes.io/name: tbml-api
  name: tbml-api
  namespace: tbml
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: tbml-api
  sessionAffinity: None
  type: ClusterIP
