apiVersion: v1
kind: Service
metadata:
  labels:
    app: tbml-app
    app.kubernetes.io/component: tbml-app
    app.kubernetes.io/instance: tbml-app
    app.kubernetes.io/name: tbml-app
  name: tbml-app
  namespace: tbml
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: tbml-app
  sessionAffinity: None
  type: ClusterIP
